### ISSUE TITLE
UITabBar* not implemented

### ISSUE THREAD

**Issue by tbrannam** [BigZaphod/Chameleon#18]
I see that UITabBar\* is not implemented.  I have started this work.

**Comment by steipete** [comment]
I've added the skeletons on this, you can use http://parsekit.com/umekit/ as an inspiration.

**Comment by cmelbye** [comment]
This would be really nice. It seems like Apple could be moving towards something like this for their Mac OS X apps. For example, see the Mac App Store and its tab bar at the top. Something that looks similar to that would be pretty good I think.

**Comment by steipete** [comment]
Yeah, maybe we see something like this in Lion. But it doesn't look like they release their UIKit, and even then, until we can drop SL this project is the best chance we have.

**Comment by zwaldowski** [comment]
How Chameleon will treat this and things like it?  (I haven't been able to try a build; my Mac has been inaccessible.)  Would a UITabBar implementation more resemble UMEKit and iOS, or would it be more Mac-like a la the App Store?

**Comment by BigZaphod** [comment]
The closest example that I know of for a UITabBarController is Facetime for OS X. Facetime is the most iOS-like app I can think of that Apple has produced. I don't know if that hints that they are thinking about going this direction on the desktop or not, though.

I don't think it makes sense to try to put the tabs on the top of the view or anything like that since often you see UINavigationControllers embedded in a UITabBarController. If the tabs were at the top, you'd have a very visually heavy top half of the view (tab bar + navigation bar). Also a lot of designs would simply not work right, I suspect.

Keep in mind that Chameleon isn't necessarily about porting over iOS apps with zero effort and having them feel native automatically. Devs are going to have to put some effort into reworking certain parts of their UI to "fit" better on OS X and that might sometimes mean simply not using things like UITabBarController when building for the desktop. That said, though, Chameleon should have it available because, as I said before, Facetime shows that it can work even on OS X and the choice in this case might be best left up to the third party dev for defining what experience they want on the desktop vs. iOS.

**Comment by tbrannam** [comment]
I have basic functionality of UITabBar and UITabBarController working -- not including TabBar customization.   Still a work in progress - but interested parties can look at the TabBar example in my fork
