### ISSUE TITLE
New Name needed; Chameleon already used for OS X software project

### ISSUE THREAD

**Issue by jaxparo** [BigZaphod/Chameleon#3]
This project needs a new name, Chameleon has already been taken by another OS software project for the past several years already. Please don't create more confusion and problems, just change the name to something else, problem solved.
http://chameleon.osx86.hu/

**Comment by BigZaphod** [comment]
It's unfortunate that there's a naming conflict. We didn't notice initially because we used the Chameleon name internally for awhile, got used to it, made a logo, etc. and then ended up releasing it all publicly. None of us had ever heard of the bootloader project prior to yesterday and because we didn't consider this a "product" in the usual sense, no one thought to do an exhaustive name search or anything.

We have a lot invested in the name now in the form of publicity, a mascot, etc. It is unlikely we will be changing the name in the near future. While an unfortunate thing, anyone looking for the chameleon bootloader is likely to use the word "bootloader" at some point in a search and they will have no problem finding it that way, IMO.

**Comment by jaxparo** [comment]
The reasons listed for not changing the name are really poor reasons. First of all, the mascot is terrible, one of the worst I've ever seen, so there's no great loss there. Second, while the admission "no one thought to do an exhaustive name search or anything" makes the error seem inadvertent, it's still an error. What if you said "we used the Apple name internally for a while" as justification for inadvertently calling your product Apple. Does this make any sense whatsoever?
Google changed their name (was called "BackRub" first), and they purposefully misspelled "Googol" to avoid creating the exact same confusion you're now defending. It's bad karma to steal another project's name. You're starting off on the wrong foot. The reasons cited for doing so are selfish, illogical, and indefensible on any moral grounds. Just change the name to something else, problem solved.

**Comment by steipete** [comment]
Jaxparo, you're a bit harsh here. And you can't compare it with Apple - they have a trademark on the name, I assume you don't.

Next, from my point of view, the mascot is great. It's original and rememberable.

It's unfortunate that there's a name conflict as both are mac projects, but they're in different areas, so it's okay. And looking at your site they could have easily assumed the project is dead, when the latest post is from 2009.

There's also a Chameleon CMS, a Chameleon Template Engine, a Chameleon Clock, a dozen of Chameleon Games, a Chameleon Photo App, a Chameleon Startup Manager, Chameleon Drivers, Skins and more. There's even a PSP game called Chameleon. So it's not something where you have the monopoly on the name.
